export const START_FETCHING_TALENTS = "redux/TALENTS/START_FETCHING_TALENTS";
export const SUCCESS_FETCHING_TALENTS =
  "redux/TALENTS/SUCCESS_FETCHING_TALENTS";
export const ERROR_FETCHING_TALENTS = "redux/TALENTS/ERROR_FETCHING_TALENTS";
export const SET_KEYWORD = "redux/talents/SET_KEYWORD";
